### ISSUE TITLE
USER STORY: Delete comments in a post

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/terok-nor-station#18]
As a **User** I can **delete a comment in a post** so that **it doesn't exist anymore and can't be viewed**

Acceptance Criteria
- The option should be done by a button
-  When clicked it should give the option for the user if they want to delete the comment or go back
- Have it that the user can only deleted their own comments

Tasks
- [x] Create the button for deletion
- [x] Have it give the choice for the deletion or not
- [x] Redirect the user back to the post it was deleted on, if delted
- [x] Redirect back to the post if they choose to go back
