### ISSUE TITLE
USER STORY: Add to database

### ISSUE THREAD

**Issue by IzzyLeech** [IzzyLeech/terok-nor-station#3]
As a **Site User** I can **be able to add information about my Star Trek DS9** so that **so that I can share my knowledge and insights with other fans.**
Accepatancve Criteria
- Have an input that will allow the user to submit a request to add information
- Show a form that is required data that the user must enter
- Have a input the will submit the request to add

Tasks
- [x]  Create a button for the user to submit information
- [x] Render a for for the user to add data to
- [x] Create a button that will submit the form for requuest
